/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smiletalk.web.form;

import org.apache.struts.action.ActionForm;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 02-04-2013
 * 
 * XDoclet definition:
 * @struts.form name="albumForm"
 */
public class AlbumForm extends ActionForm {
	
	private String id;
	private String name;
	private String descript;
	private String whoSee;
	
	private String photoComment;
	
	public String getPhotoComment() {
		return photoComment;
	}
	public void setPhotoComment(String photoComment) {
		this.photoComment = photoComment;
	}
	//album name
	private String photoName;
	//photo formfile name
	private FormFile photo1;
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getDescript() {
		return descript;
	}
	public void setDescript(String descript) {
		this.descript = descript;
	}
	public String getWhoSee() {
		return whoSee;
	}
	public void setWhoSee(String whoSee) {
		this.whoSee = whoSee;
	}
	public String getPhotoName() {
		return photoName;
	}
	public void setPhotoName(String photoName) {
		this.photoName = photoName;
	}
	public FormFile getPhoto1() {
		return photo1;
	}
	public void setPhoto1(FormFile photo1) {
		this.photo1 = photo1;
	}
	public FormFile getPhoto2() {
		return photo2;
	}
	public void setPhoto2(FormFile photo2) {
		this.photo2 = photo2;
	}
	public FormFile getPhoto3() {
		return photo3;
	}
	public void setPhoto3(FormFile photo3) {
		this.photo3 = photo3;
	}
	public FormFile getPhoto4() {
		return photo4;
	}
	public void setPhoto4(FormFile photo4) {
		this.photo4 = photo4;
	}
	public FormFile getPhoto5() {
		return photo5;
	}
	public void setPhoto5(FormFile photo5) {
		this.photo5 = photo5;
	}
	private FormFile photo2;
	private FormFile photo3;
	private FormFile photo4;
	private FormFile photo5;
	
	
}