/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smiletalk.web.form;

import org.apache.struts.action.ActionForm;

import com.smiletalk.domain.User;

public class ArticleForm extends ActionForm {
	
	private Integer articleId;
	private Integer readNumber;
	private String title;
	private String content;
	
	private String articleComment;
	
	public String getArticleComment() {
		return articleComment;
	}
	public void setArticleComment(String articleComment) {
		this.articleComment = articleComment;
	}
	public Integer getArticleId() {
		return articleId;
	}
	public void setArticleId(Integer articleId) {
		this.articleId = articleId;
	}
	public Integer getReadNumber() {
		return readNumber;
	}
	public void setReadNumber(Integer readNumber) {
		this.readNumber = readNumber;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	
	
	
	
}