/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smiletalk.web.form;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.smiletalk.domain.User;

public class GossipForm extends ActionForm {
	
	public Integer getGetId() {
		return getId;
	}
	public void setGetId(Integer getId) {
		this.getId = getId;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	private Integer getId;
	private String content;
	
	
	
}