/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smiletalk.web.form;

import org.apache.struts.action.ActionForm;

import com.smiletalk.domain.User;

/** 
 * MyEclipse Struts
 * Creation date: 03-03-2013
 * 
 * XDoclet definition:
 * @struts.form name="newsForm"
 */
public class NewsForm extends ActionForm {
	
	private Integer id;
	private String content;
	private String comment;
	public String getComment() {
		return comment;
	}
	public void setComment(String comment) {
		this.comment = comment;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	
	
}