/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smiletalk.web.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.smiletalk.domain.User;
import com.smiletalk.service.inter.UserServiceInter;
import com.smiletalk.web.form.UserForm;

public class LoginAction extends DispatchAction {
	
	private UserServiceInter userService; 
	
	
	public void setUserService(UserServiceInter userService) {
		this.userService = userService;
	}

	public ActionForward logout(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		//request.getSession().invalidate();
		return mapping.findForward("logout");
		
	}

	public ActionForward login(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm userForm = (UserForm) form;// TODO Auto-generated method stub
		// one way
		//userService.getResult("from Users where email=? and pwd=?", new Object[]{userForm.getEmail(),userForm.getPwd()});
		
		// in MVC mode
		User user=new User();
		
		//System.out.println(userForm.getEmail()+"  "+userForm.getPwd());
		
		user.setEmail(userForm.getEmail());
		user.setPwd(userForm.getPwd());
		user=userService.check(user);
		if(user!=null){
			//legal and save user to bean
			request.getSession().setAttribute("user", user);		
			return mapping.findForward("goHomeUI");
		}else{
			//illegal
			return mapping.findForward("goIndexUI");
		}
		
	}
}