/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smiletalk.web.action;

import java.util.Date;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.smiletalk.domain.Friend;
import com.smiletalk.domain.News;
import com.smiletalk.domain.NewsComment;
import com.smiletalk.domain.User;
import com.smiletalk.service.inter.FriendServiceInter;
import com.smiletalk.service.inter.NewsCommentServiceInter;
import com.smiletalk.service.inter.NewsServiceInter;
import com.smiletalk.service.inter.UserServiceInter;
import com.smiletalk.web.form.NewsForm;


/** 
 * MyEclipse Struts
 * Creation date: 03-03-2013
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */
public class NewsAction extends DispatchAction {
	
	private UserServiceInter userService; 
	private NewsServiceInter newsService;
	private NewsCommentServiceInter newsCommentService;
	public void setNewsCommentService(NewsCommentServiceInter newsCommentService) {
		this.newsCommentService = newsCommentService;
	}


	private FriendServiceInter friendService;
	
	public void setUserService(UserServiceInter userService) {
		this.userService = userService;
	}

	public void setNewsService(NewsServiceInter newsService) {
		this.newsService = newsService;
	}

	public void setFriendService(FriendServiceInter friendService) {
		this.friendService = friendService;
	}
	
	
	public ActionForward AddNews(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
        User user=(User) request.getSession().getAttribute("user");
		
		NewsForm newsForm=(NewsForm) form;
	    News news=new News();	
	    news.setNewsId(newsForm.getId());
	    news.setContent(newsForm.getContent());
	    news.setUser(user);
	    news.setIndate(new Date());
	    
	    newsService.save(news);
	    
	    List newsList=newsService.getResult("from News where 1=? order by id desc", new Object[]{1});
		request.setAttribute("newsList", newsList);
		
		List peopleList=userService.getResult("from User where userId <> ?", new Object[]{Integer.valueOf(user.getUserId())});
		request.setAttribute("peopleList", peopleList);
		
		List friendList=friendService.getResult("from Friend where hostId=?", new Object[]{Integer.valueOf(user.getUserId())});
		request.setAttribute("friendList", friendList);
		
		return mapping.findForward("goHomeUI");
	}
		

	public ActionForward AddNewsComment(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		User user=(User) request.getSession().getAttribute("user");
		
		NewsForm newsForm=(NewsForm) form;
		
		News news=(News)newsService.findById(News.class, Integer.valueOf(newsForm.getId()));
		
		
	    NewsComment newsComment=new NewsComment();	
	   
	    newsComment.setComment(newsForm.getComment());
	    newsComment.setIndate(new Date());
	    newsComment.setNews(news);
	    
	    newsCommentService.save(newsComment);
	   
	    List newsList=newsService.getResult("from News where 1=? order by id desc", new Object[]{1});
		request.setAttribute("newsList", newsList);
		
		List peopleList=userService.getResult("from User where userId <> ?", new Object[]{Integer.valueOf(user.getUserId())});
		request.setAttribute("peopleList", peopleList);
		
		List friendList=friendService.getResult("from Friend where hostId=?", new Object[]{Integer.valueOf(user.getUserId())});
		request.setAttribute("friendList", friendList);
		
		return mapping.findForward("goHomeUI");
	}
}