/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smiletalk.web.action;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.smiletalk.service.inter.CityServiceInter;
import com.smiletalk.service.inter.CountryServiceInter;
import com.smiletalk.service.inter.UniversityServiceInter;

/** 
 * MyEclipse Struts
 * Creation date: 01-14-2013
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */

  

public class RegisterAction extends DispatchAction {
	
	@Resource
	private CountryServiceInter countryService;
	
	private CityServiceInter cityService;

	private UniversityServiceInter universityService;
	
	//jump to register page UI-user interface
	public ActionForward regUI(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		//register successful then jump to home.jsp
		
		//prepare data when user choose university
		
		
		//country
		request.setAttribute("countrylist", countryService.getResult("from Country where coId=?", new Object []{new Integer(76)}));
		//school city
		request.setAttribute("citylist", cityService.getResult("from City", null));
		
		//university name, first set as helsingki
		request.setAttribute("unilist", universityService.getResult("from University where city.ciId=?", new Object []{new Integer(1)}));
		
		return mapping.findForward("regUI");
	}
	
	//register
	public ActionForward regUser(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		//register successful then jump to home.jsp
		
		
		
		
		return mapping.findForward("regok");
	}


	public void setCityService(CityServiceInter cityService) {
		this.cityService = cityService;
	}
	
	public void setCountryService(CountryServiceInter countryService) {
		this.countryService = countryService;
	}

	public void setUniversityService(UniversityServiceInter universityService) {
		this.universityService = universityService;
	}
}