/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smiletalk.web.action;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;


import com.smiletalk.service.TestService;

/** 
 * MyEclipse Struts
 * Creation date: 01-14-2013
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */

public class TestAction extends DispatchAction {
	
	@Resource
	private TestService testService;
	
	public void setTestService(TestService testService) {
		this.testService = testService;
	}

	public ActionForward test(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		/*WebApplicationContext ctx=WebApplicationContextUtils.getWebApplicationContext(this.getServlet().getServletContext());
		TestService ts=(TestService) ctx.getBean("testService");
		*/
		List list=testService.showCountry();
		request.setAttribute("list", list);
		return mapping.findForward("show");
	}
}